# Rachel Ward

## DAV 5400 Assignment 4


### Task 1

"1. Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it."

For this task, I searched for built in numpy functions that provide the intersection and came across https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.intersect1d.html I then passed the two arrays we had to get the intersection.

In [2]:
#first import numpy
import numpy as np

#next list arrays that we have already defined above
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]) 

#use numpy intersect1d function and pass our two arrays to get the intersection of the arrays.
np.intersect1d(a,b)

array([2, 4])

### Task 2

"2. Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you
do not need to explicitly key in every integer value.
> 1 6 11<br>
> 2 7 12<br>
> 3 8 13<br>
> 4 9 14<br>
> 5 10 15<br> 

For this task I will create an array with numbers 1 - 15 using numpy's arange function. I will then use the .reshape() function to make it a 3 x 5 array. Lastly I will use the transpose function to make it into a 5 x 3 array. This will give us the numbers in the correct space.

In [3]:
#use arange, reshape, and transpose functions to generate the array in the format desired.
np.arange(1,16).reshape(3,5).transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

### Task 3
"3. You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b."

To do this I will use numpy's built in setdiff1d function which returns values that are present in array a but not in array b.


In [4]:
#first create the given arrays
a = np.array([12,5,7,15,3,1,8])
b = np.array([14,6,3,11,19,12,5])

#use numpy setdiff1d function to find items that are unique to array a
np.setdiff1d(a,b)


array([ 1,  7,  8, 15])

## Task 4

"4. Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows the total
miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two entries might
be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is to create a
NumPy array wherein you can record the cumulative miles you recorded each day during your trip. Then use your
Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and included at
least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal
fatigue/soreness. For the remaining 31 days, you would have covered the entire distance between NYC and Key West.
Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your
approach to this problem, including the ways in which you decided to make use of NumPy."

For this task, I first used google maps to map the distance between New York, NY and Key West, FL, selecting the bicycle option. Google maps indicated that the route involved a ferry, and that the total distance by bicycle was 1,547 miles. I then created x as a variable for that amount, and set the distances traveled so far to 0. I created an empty list to which I will add the cumulative distance traveled every day (the odometer readings). I will then convert this list to an array using numpy. I will use the numpy diff function to parse out the distance traveled each day, but this will only give me the difference for days 2 - 35, not the first day. So finally I will use the numpy.insert function to insert the number of miles traveled on the first day.


In [29]:
#set the number of miles to travel, 1,547 as x
x = 1547

#set the distance you have traveled so far as 0
distancesofar = 0

#create an empty list that we will use to store the odometer readings
distance_traveled= []

#use a for loop to add the odometer readings to the empty list created above.
for i in range(34):
    if i == 0: #travel 17 miles the first day so that the remainder of the days will be a nice, even distance.
        Distancetraveledtoday = 17
        distancesofar = Distancetraveledtoday
        distance_traveled.append(distancesofar)
    if i in (5,10,15,30): #set four days for which there will be 0 distance traveled
        Distancetraveledtoday = 0
        distancesofar = distancesofar + Distancetraveledtoday
        distance_traveled.append(distancesofar)
    else:
        Distancetraveledtoday = int((x-17) /(30)) #since x was 1547 and we already traveled 17 miles, divide the remaining distance by 30 to get the miles per day
        distancesofar = distancesofar + Distancetraveledtoday
        distance_traveled.append(distancesofar);

#check to make sure our last day is 1547.
print(distance_traveled)

#use numpy to convert our list into an array
distance_traveled_array = np.array(distance_traveled)  
#return the array to make sure it is correct
distance_traveled_array

#use numpy diff function to find the difference between successive elements (i.e. element 1 - element 0) in order to get the distance traveled each day
distance_each_day = np.diff(distance_traveled_array)
distance_each_day

#use the numpy insert function to insert 17 miles for the element 0 in the new array because we know we traveled 17 miles the first day
distance_each_day = np.insert(distance_each_day, 0,17)
#return resulting array of distance traveled each day
distance_each_day

[17, 68, 119, 170, 221, 272, 272, 323, 374, 425, 476, 476, 527, 578, 629, 680, 680, 731, 782, 833, 884, 935, 986, 1037, 1088, 1139, 1190, 1241, 1292, 1343, 1394, 1394, 1445, 1496, 1547]


array([17, 51, 51, 51, 51, 51,  0, 51, 51, 51, 51,  0, 51, 51, 51, 51,  0,
       51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51,  0, 51, 51,
       51])

## Task 5

"5. Open the Jupyter Notebook provided to you with this assignment. The first code block within that file will load a
small data set from a GitHub repository into a NumPy 2D array. The original source of that data contains an overview of
its contents:
https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m
Scroll down to the bottom of that page to access an interactive data viewer that includes the column headings for the
data.
Using the NumPy array that has been loaded for you in the Jupyter Notebook, answer the following questions using
NumPy’s slicing, methods, and functions:
 What is the maximum yearly NYC consumption of water in millions of gallons per day?
 How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.
 What is the mean and the standard deviation of the per capita daily water consumption?
 What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.
Please note that it may take a bit of time for Jupyter to load the data set from the GitHub repository. You will know that
process has finished once the results of the ‘type(nyc_water)’ command get displayed within your copy of the
notebook."

Immediately below I executed the code from the jupyter notebook. I split this task into subtasks based on the questions and offer further details as to how I solved those questions in markdown cells below.

In [36]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

C:\Users\sheri\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

### Task 5 Question 1:
"What is the maximum yearly NYC consumption of water in millions of gallons per day?"

For this task I will use Numpy's max function and then use indexing to get the max for only the 3rd column which contains the NYC consumption of water in millions of gallons per day.

In [66]:
#Use the numpy max function and indexing to get the element at index 2 - in the 3rd column
maxwater = np.max(nyc_water, 0)[2]

#print results
print("The maximum yearly NYC consumption of water in millions of gallons per day is ", maxwater)

The maximum yearly NYC consumption of water in millions of gallons per day is  1512.0


### Task 5 - Question 2

"How many calendar years are represented within this data set? NumPy's shape command is one way to find out."

For this question I will use the numpy size function which allows me to choose either the number of columns or the number of rows, rather than the shape function which returns both.

In [49]:
#Use the Numpy size function so that I will can choose to get only the number of rows rather than rows + columns.
num_of_years = np.size(nyc_water,0)

#print the results
print("The number of years present is ", num_of_years)

The number of years present is  39


### Task 5 - Question 3
"What is the mean and the standard deviation of the per capita daily water consumption?"

To solve this I will use numpy's mean and standard deviation functions and then use indexing to get the result for the last column. 

In [68]:
#use the numpy mean function to determine the mean of each column and slice that result for only the last column
meanpc = np.mean(nyc_water,0)[-1]

#print results
print("The mean per capita daily water consumption is ", meanpc)

#use the numpy .std function to find the standard deviation for each column and then slice that result for only the last column
stdpc = np.std(nyc_water,0)[-1]

#print results
print("The standard deviation of the per capita daily water consumption is ", stdpc)

The mean per capita daily water consumption is  160.30769230769232
The standard deviation of the per capita daily water consumption is  31.51894330370624


### Task 5 - Question 4
"What is the increase or decrease in population from year to year? Use NumPy's diff function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen."

Because using the diff function on a multidimensional array makes little sense in this scenario, I first created a new array called pop, made up of the 2nd column (index 1) of the nyc_water array. Then I used the diff function to create another array with just the differences between the elements of my new array. I then returned those results.

In [69]:
#first we need to get only the population column from the array so we use Numpy's slicing features to pull column index 1.
pop = nyc_water[:,1]

#then we use numpy's diff function to find the difference between the elements and return that in a new array
pop_diff = np.diff(pop)

#return results
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])